# Set base image.
FROM eclipse-temurin

# Copy SoundLevelMonitor.java from folder where this dockerfile is located into container's root directory.
COPY SoundLevelMonitor.java .

# Compile SoundLevelMonitor (this is executed only once - when creating a container from a docker image generated by this dockerfile).
RUN javac SoundLevelMonitor.java

# Create a shared folder for mounting input and output files.
RUN mkdir shared-folder

# Start SoundLevelMonitor (this is executed every time a container created from a docker image generated by this dockerfile gets started).
CMD java SoundLevelMonitor